server:
  port: 7000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-coupon
mybatis-plus:
  #mapper下的任意路径下的所有xml,classpath后面带一个*代表不止扫描自己的类路径，还扫描引用的其他依赖的jar包的类路径；可以只精确地写自己
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
coupon:
  user:
    name: "test"
    age: 18